export const PROJECTS = [
  {
    id: 1,
    link: "https://terjeee.github.io/2022-02-12-GuessNumber/",
    linkRepo: "https://github.com/terjeee/2022.02.12-GuessNumber",
    title: "Guess the Number",
    colorDot: "#F1E05A",
    text: "Javascript | NB: bare for større skjermer",
  },
  {
    id: 2,
    link: "https://terjeee.github.io/2022.05.27-Advice-Generator/",
    linkRepo: "https://github.com/terjeee/2022.05.27-Advice-Generator",
    title: "Advice Generator",
    colorDot: "#563D7C",
    text: "Javascript, API",
  },
  {
    id: 3,
    link: " https://terjeee.github.io/2022-08-10-calculator-app/",
    linkRepo: "https://github.com/terjeee/2022-08-10-calculator-app",
    title: "Calculator",
    colorDot: "#F1E05A",
    text: "React",
  },
  {
    id: 4,
    link: "https://terjeee.github.io/2022-08-21-bank-landing-page/",
    linkRepo: "https://github.com/terjeee/2022-08-21-bank-landing-page",
    title: "EasyBank",
    colorDot: "#F1E05A",
    text: "React, React Router",
  },
  {
    id: 5,
    link: "https://terjeee.github.io/2022-08-14-ip-address-tracker/",
    linkRepo: "https://github.com/terjeee/2022-08-14-ip-address-tracker",
    title: "IP Address Tracker",
    colorDot: "#F1E05A",
    text: "React, API",
  },
  {
    id: 6,
    link: "https://terjeee.github.io/2022-09-04-rest-countries-api/",
    linkRepo: "https://github.com/terjeee/2022-09-04-rest-countries-api",
    colorDot: "#F1E05A",
    title: "Countries API",
    text: "React, React Router, SCSS, API, localStorage, ",
  },
  {
    id: 7,
    link: "https://terjeee.github.io/to-do/",
    linkRepo: "https://github.com/terjeee/to-to/",
    colorDot: "#3178c6",
    title: "To-do List",
    text: "Typescript, Redux, SCSS, localStorage",
  },
];
