export const PROJECTS = [
  {
    id: 1,
    link: "https://terjeee.github.io/2022-09-04-rest-countries-api/",
    linkRepo: "https://github.com/terjeee/2022-09-04-rest-countries-api",
    colorDot: "#F1E05A",
    title: "Countries API",
    text: "Pulls data from an API. Each country has a separate route with more details.",
  },
  {
    id: 2,
    link: "https://terjeee.github.io/2022-08-14-ip-address-tracker/",
    linkRepo: "https://github.com/terjeee/2022-08-14-ip-address-tracker",
    title: "IP Address Tracker",
    colorDot: "#F1E05A",
    text: "Shows the location of an IP address on a map.",
  },
  {
    id: 3,
    link: "https://terjeee.github.io/2022-08-21-bank-landing-page/",
    linkRepo: "https://github.com/terjeee/2022-08-21-bank-landing-page",
    title: "EasyBank",
    colorDot: "#F1E05A",
    text: "Dummy landing page for a bank.",
  },
  {
    id: 4,
    link: " https://terjeee.github.io/2022-08-10-calculator-app/",
    linkRepo: "https://github.com/terjeee/2022-08-10-calculator-app",
    title: "Calculator",
    colorDot: "#F1E05A",
    text: ":)",
  },
  {
    id: 5,
    link: "https://terjeee.github.io/2022.05.27-Advice-Generator/",
    linkRepo: "https://github.com/terjeee/2022.05.27-Advice-Generator",
    title: "Advice Generator",
    colorDot: "#563D7C",
    text: "Pulls advice from an API.",
  },
  {
    id: 6,
    link: "https://terjeee.github.io/2022.02.12-GuessNumber/",
    linkRepo: "https://github.com/terjeee/2022.02.12-GuessNumber",
    title: "Guess the Number",
    colorDot: "#F1E05A",
    text: "(:",
  },
];
